// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeleteOutputFolders
{
    internal sealed partial class Vsix
    {
        public const string Id = "DeleteOutputFolders.4ea4e356-474f-4450-938e-874aca8d2ba1";
        public const string Name = "DeleteOutputFolders";
        public const string Description = @"Deletes all bin and obj folders in the solution directory.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Michael Bakker";
        public const string Tags = "";
    }
}
