// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeleteOutputFolders
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DeleteOutputFoldersString = "970ca810-af38-4ea4-82c1-96d70161db8e";
        public static Guid DeleteOutputFolders = new Guid(DeleteOutputFoldersString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int DeleteOutputFoldersGroup = 0x0001;
        public const int DeleteOutputFoldersCommand = 0x0100;
    }
}