// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionCleanup
{
    internal sealed partial class Vsix
    {
        public const string Id = "SolutionCleanup.4ea4e356-474f-4450-938e-874aca8d2ba1";
        public const string Name = "SolutionCleanup";
        public const string Description = @"Performs a configurable, thorough cleanup of all projects in the active solution.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Michael Bakker";
        public const string Tags = "solution, clean, cleanup";
        public const bool IsPreview = false;
    }
}
