// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionCleanup
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SolutionCleanupString = "970ca810-af38-4ea4-82c1-96d70161db8e";
        public static Guid SolutionCleanup = new Guid(SolutionCleanupString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SolutionCleanupGroup = 0x0001;
        public const int SolutionCleanupCommand = 0x0100;
    }
}